name: macOS 12

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }}
    runs-on: macos-12
    strategy:
      matrix:
        LLVM_VERSION: [12.0.0, 13.0.0, 14.0.0, 15.0.0]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup OS
        run: |
          brew install gnu-tar
          sudo ln -s /usr/local/bin/gtar /usr/local/bin/tar
          pip3 install ansible
      - name: Prepare working directory
        run: |
          sudo mkdir -p /opt
          sudo chown -R `whoami` /opt
      - name: Download LLVM
        run: |
          cd ci && \
          ansible-playbook download-llvm.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=macOS-12 \
            -e host=localhost \
            --verbose
      - name: Build and run tests
        run: |
          cd ci && \
          ansible-playbook build.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=macOS-12 \
            -e host=localhost \
            -e source_dir=$PWD/.. \
            --verbose
