name: macOS 10.14

on:
  pull_request:
  push:
    branches:
      - master

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }}
    runs-on: macos-10.15
    strategy:
      matrix:
        LLVM_VERSION: [6.0.0, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup OS
        run: |
          brew install gnu-tar
          sudo ln -s /usr/local/bin/gtar /usr/local/bin/tar
          pip3 install ansible
      - name: Prepare working directory
        run: |
          sudo mkdir -p /opt
          sudo chown -R `whoami` /opt
      - name: Download LLVM
        run: |
          cd ci && \
          ansible-playbook download-llvm.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=macOS-10.14 \
            -e host=localhost \
            --verbose
      - name: Build and run tests
        run: |
          cd ci && \
          ansible-playbook build.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=macOS-10.14 \
            -e host=localhost \
            -e source_dir=$PWD/.. \
            --verbose
      - name: Upload code coverage
        run: |
          curl -s https://codecov.io/bash > codecov.sh
          bash codecov.sh -f /opt/debug-coverage.lcov || echo "No debug coverage"
          bash codecov.sh -f /opt/release-coverage.lcov || echo "No release coverage"