name: CI Ubuntu 20.04

on: [pull_request]

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }}
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    strategy:
      matrix:
        LLVM_VERSION: [11.0.0]

    steps:
      - name: Install software
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt-get update && apt-get install -y python3-pip curl git cmake \
            libz-dev ncurses-dev libstdc++6 liblzma-dev
          pip3 install ansible
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Prepare working directory
        run: |
          mkdir -p /opt
      - name: Download LLVM
        run: |
          cd ci && \
          ansible-playbook download-llvm.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=ubuntu-20.04 \
            -e host=localhost \
            --verbose
      - name: Build and run tests
        run: |
          cd ci && \
          ansible-playbook build.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=ubuntu-20.04 \
            -e host=localhost \
            -e source_dir=$PWD/.. \
            --verbose
