name: CI Ubuntu 18.04

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }}
    runs-on: ubuntu-18.04
    container: ubuntu:18.04
    strategy:
      matrix:
        LLVM_VERSION: [6.0.0, 7.0.0, 8.0.0, 9.0.0, 10.0.0]

    steps:
      - name: Install software
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt-get update && apt-get install -y python-pip curl git cmake \
            libz-dev ncurses-dev libstdc++6 liblzma-dev
          pip install ansible
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Prepare working directory
        run: |
          mkdir -p /opt
      - name: Download LLVM
        run: |
          cd ci && \
          ansible-playbook download-llvm.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=ubuntu-18.04 \
            -e host=localhost \
            --verbose
      - name: Build and run tests
        run: |
          cd ci && \
          ansible-playbook build.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e platform=ubuntu-18.04 \
            -e host=localhost \
            -e source_dir=$PWD/.. \
            --verbose
      - name: Upload code coverage
        run: |
          curl -s https://codecov.io/bash > codecov.sh
          bash codecov.sh -f /opt/debug-coverage.lcov || echo "No debug coverage"
          bash codecov.sh -f /opt/release-coverage.lcov || echo "No release coverage"
